# Generated by Django 6.0 on 2026-04-28 20:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('replicate_key', models.CharField(blank=True, help_text='Replicate AI API Key', max_length=255, null=True)),
                ('openai_key', models.CharField(blank=True, help_text='OpenAI API Key (İsteğe Bağlı)', max_length=255, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='api_credentials', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PipelineConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active_design_models', models.JSONField(blank=True, default=list, help_text="Örn: ['flux-schnell', 'seedream']")),
                ('enable_upscale', models.BooleanField(default=True, help_text='Upscale adımı aktif mi?')),
                ('upscale_model', models.CharField(default='recraft-crisp', help_text='Kullanılacak upscale modeli', max_length=100)),
                ('enable_bg_removal', models.BooleanField(default=True, help_text='Arka plan silme aktif mi?')),
                ('bg_removal_model', models.CharField(default='bria-rmbg', help_text='Kullanılacak BG silme modeli', max_length=100)),
                ('enable_seo', models.BooleanField(default=True, help_text='SEO üretimi aktif mi?')),
                ('seo_text_model', models.CharField(default='gpt-4o', help_text='Yazı üretimi için model (gpt-4o vb.)', max_length=100)),
                ('seo_vision_model', models.CharField(default='gpt-4o-vision', help_text='Görsel analiz modeli', max_length=100)),
                ('title_system_prompt', models.TextField(blank=True, help_text='Title için GPT Sistem Promptu', null=True)),
                ('tags_system_prompt', models.TextField(blank=True, help_text='Tags için GPT Sistem Promptu', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pipeline_config', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_premium', models.BooleanField(default=False, help_text='Kullanıcı Premium üye mi?')),
                ('subscription_end_date', models.DateTimeField(blank=True, null=True)),
                ('theme_preference', models.CharField(choices=[('light', 'Light'), ('dark', 'Dark')], default='light', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
