# Generated by Django 6.0 on 2026-05-02 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pipelineconfig',
            name='dynamic_config',
            field=models.JSONField(blank=True, default=dict, help_text='Arayüzden gelen tüm detaylı JSON yedeği'),
        ),
        migrations.AlterField(
            model_name='pipelineconfig',
            name='bg_removal_model',
            field=models.CharField(default='bria-rmbg', max_length=100),
        ),
        migrations.AlterField(
            model_name='pipelineconfig',
            name='enable_bg_removal',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='pipelineconfig',
            name='enable_seo',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='pipelineconfig',
            name='enable_upscale',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='pipelineconfig',
            name='seo_text_model',
            field=models.CharField(default='gpt-4o', max_length=100),
        ),
        migrations.AlterField(
            model_name='pipelineconfig',
            name='seo_vision_model',
            field=models.CharField(default='gpt-4o-vision', max_length=100),
        ),
        migrations.AlterField(
            model_name='pipelineconfig',
            name='tags_system_prompt',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pipelineconfig',
            name='title_system_prompt',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pipelineconfig',
            name='upscale_model',
            field=models.CharField(default='recraft-crisp', max_length=100),
        ),
    ]
