# Generated by Django 6.0 on 2026-05-02 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_pipelineconfig_dynamic_config_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pipelineconfig',
            old_name='tags_system_prompt',
            new_name='detection_prompt',
        ),
        migrations.RenameField(
            model_name='pipelineconfig',
            old_name='title_system_prompt',
            new_name='gen_model_1_prompt',
        ),
        migrations.RenameField(
            model_name='pipelineconfig',
            old_name='seo_text_model',
            new_name='seo_model',
        ),
        migrations.RenameField(
            model_name='pipelineconfig',
            old_name='seo_vision_model',
            new_name='vision_model',
        ),
        migrations.RemoveField(
            model_name='pipelineconfig',
            name='active_design_models',
        ),
        migrations.AddField(
            model_name='pipelineconfig',
            name='detection_model',
            field=models.CharField(default='grounding-dino', max_length=100),
        ),
        migrations.AddField(
            model_name='pipelineconfig',
            name='enable_detection',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='pipelineconfig',
            name='enable_generation',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='pipelineconfig',
            name='enable_vision',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='pipelineconfig',
            name='gen_model_1_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='pipelineconfig',
            name='gen_model_1_id',
            field=models.CharField(default='flux-2-pro', max_length=50),
        ),
        migrations.AddField(
            model_name='pipelineconfig',
            name='gen_model_2_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='pipelineconfig',
            name='gen_model_2_id',
            field=models.CharField(default='seedream-4.5', max_length=50),
        ),
        migrations.AddField(
            model_name='pipelineconfig',
            name='gen_model_2_prompt',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pipelineconfig',
            name='gen_model_3_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='pipelineconfig',
            name='gen_model_3_id',
            field=models.CharField(default='nano-banana', max_length=50),
        ),
        migrations.AddField(
            model_name='pipelineconfig',
            name='gen_model_3_prompt',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pipelineconfig',
            name='seo_tags_system_prompt',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pipelineconfig',
            name='seo_title_system_prompt',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pipelineconfig',
            name='seo_user_prompt',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pipelineconfig',
            name='vision_system_prompt',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pipelineconfig',
            name='vision_user_prompt',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pipelineconfig',
            name='dynamic_config',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
