# Generated by Django 6.0 on 2026-04-28 20:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ai', '0001_initial'),
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MockupGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mockup_groups', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MockupItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('mockup_image', models.ImageField(upload_to='mockups/items/')),
                ('placement_data', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='image_processor.mockupgroup')),
            ],
        ),
        migrations.CreateModel(
            name='MockupResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result_image', models.ImageField(upload_to='mockups/results/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('design_variation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mockup_results', to='ai.designvariation')),
                ('manual_upload', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mockup_results', to='products.manualupload')),
                ('mockup_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='image_processor.mockupitem')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('design_variation__isnull', False), ('manual_upload__isnull', True)), models.Q(('design_variation__isnull', True), ('manual_upload__isnull', False)), _connector='OR'), name='mockup_result_one_source_only')],
            },
        ),
    ]
