# Generated by Django 6.0 on 2026-04-28 20:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('etsy', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DesignVariation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt_used', models.TextField(blank=True)),
                ('ai_model_name', models.CharField(blank=True, max_length=100)),
                ('generated_image', models.ImageField(blank=True, null=True, upload_to='designs/generated/')),
                ('upscaled_image', models.ImageField(blank=True, null=True, upload_to='designs/upscaled/')),
                ('no_bg_image', models.ImageField(blank=True, null=True, upload_to='designs/transparent/')),
                ('status', models.CharField(choices=[('pending', 'Sırada'), ('processing', 'İşleniyor'), ('completed', 'Tamamlandı'), ('failed', 'Hata'), ('approved', 'Onaylandı')], db_index=True, default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variations', to='etsy.etsyproduct')),
            ],
        ),
        migrations.CreateModel(
            name='SeoOptimization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vision_analysis', models.TextField(blank=True)),
                ('generated_title', models.CharField(blank=True, max_length=500)),
                ('generated_tags', models.TextField(blank=True)),
                ('target_keywords', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('design_variation', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seo', to='ai.designvariation')),
                ('manual_upload', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seo', to='products.manualupload')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('design_variation__isnull', False), ('manual_upload__isnull', True)), models.Q(('design_variation__isnull', True), ('manual_upload__isnull', False)), _connector='OR'), name='seo_one_source_only')],
            },
        ),
    ]
