# Generated by Django 6.0 on 2026-03-15 21:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EtsyProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(help_text='Etsy Listing URL')),
                ('title', models.CharField(blank=True, max_length=500, null=True)),
                ('description', models.TextField(blank=True, help_text='Ürün açıklaması', null=True)),
                ('price', models.CharField(blank=True, help_text='Ürün fiyatı', max_length=50, null=True)),
                ('image_url', models.URLField(blank=True, help_text="Etsy'deki orjinal ürün fotoğrafı", null=True)),
                ('local_image_path', models.CharField(blank=True, max_length=255, null=True)),
                ('cropped_image', models.ImageField(blank=True, null=True, upload_to='crops/')),
                ('tags', models.TextField(blank=True, help_text='Virgülle ayrılmış tagler', null=True)),
                ('favorites_count', models.CharField(default='0', max_length=50)),
                ('views', models.CharField(blank=True, help_text='Sepetteki veya görüntülenme sayısı', max_length=50, null=True)),
                ('item_review_count', models.CharField(blank=True, help_text='Bu ürünün yorum sayısı', max_length=50, null=True)),
                ('shop_review_count', models.CharField(blank=True, help_text='Mağazanın toplam yorum sayısı', max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='etsy_products', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'url')},
            },
        ),
        migrations.CreateModel(
            name='DesignVariation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt_used', models.TextField(blank=True, null=True)),
                ('ai_model_name', models.CharField(blank=True, help_text='Flux, Nano, Seedream vb.', max_length=100, null=True)),
                ('generated_image', models.ImageField(blank=True, null=True, upload_to='designs/generated/')),
                ('upscaled_image', models.ImageField(blank=True, null=True, upload_to='designs/upscaled/')),
                ('no_bg_image', models.ImageField(blank=True, null=True, upload_to='designs/transparent/')),
                ('status', models.CharField(choices=[('pending', 'Sırada'), ('processing', 'İşleniyor'), ('completed', 'Tamamlandı'), ('failed', 'Hata'), ('approved', 'Kullanıcı Onayladı')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variations', to='manager.etsyproduct')),
            ],
        ),
        migrations.CreateModel(
            name='SeoOptimization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generated_title', models.CharField(blank=True, max_length=500, null=True)),
                ('generated_tags', models.TextField(blank=True, null=True)),
                ('target_keywords', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='seo', to='manager.etsyproduct')),
            ],
        ),
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('replicate_api_key', models.CharField(blank=True, help_text='Kullanıcının Replicate API Anahtarı', max_length=255, null=True)),
                ('pipeline_config', models.JSONField(blank=True, default=dict, help_text='Seçili AI modelleri ve custom promptlar', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
