# Generated by Django 6.0 on 2026-04-20 21:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MockupTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Örn: Siyah Tişört Ön Yüz, Kupa Sol Taraf', max_length=100)),
                ('mockup_image', models.ImageField(upload_to='mockups/templates/')),
                ('placement_data', models.JSONField(blank=True, default=dict, help_text='Tasarımın oturacağı alanın koordinatları', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mockup_templates', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
