# Generated by Django 6.0 on 2026-04-24 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0004_manualupload_alter_seooptimization_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='manualupload',
            name='status_mockup',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='manualupload',
            name='status_seo',
            field=models.BooleanField(default=False),
        ),
    ]
