# Generated by Django 6.0 on 2026-04-25 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0005_manualupload_status_mockup_manualupload_status_seo'),
    ]

    operations = [
        migrations.AddField(
            model_name='manualupload',
            name='original_filename',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
    ]
