# Generated by Django 6.0 on 2026-04-28 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0006_manualupload_original_filename'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='etsyproduct',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='etsyproduct',
            name='user',
        ),
        migrations.RemoveField(
            model_name='seooptimization',
            name='product',
        ),
        migrations.RemoveField(
            model_name='manualupload',
            name='group',
        ),
        migrations.RemoveField(
            model_name='seooptimization',
            name='manual_upload',
        ),
        migrations.RemoveField(
            model_name='mockupgroup',
            name='user',
        ),
        migrations.RemoveField(
            model_name='mockupitem',
            name='group',
        ),
        migrations.RemoveField(
            model_name='uploadgroup',
            name='user',
        ),
        migrations.RemoveField(
            model_name='usersettings',
            name='user',
        ),
        migrations.DeleteModel(
            name='DesignVariation',
        ),
        migrations.DeleteModel(
            name='EtsyProduct',
        ),
        migrations.DeleteModel(
            name='ManualUpload',
        ),
        migrations.DeleteModel(
            name='SeoOptimization',
        ),
        migrations.DeleteModel(
            name='MockupGroup',
        ),
        migrations.DeleteModel(
            name='MockupItem',
        ),
        migrations.DeleteModel(
            name='UploadGroup',
        ),
        migrations.DeleteModel(
            name='UserSettings',
        ),
    ]
